# /configs/model.yaml

llama3:
    ollama:
        small: 'crewai-llama3'
        # medium: 'crewai-llama3-70b'
    groq:
        small: 'llama3-8b-8192'
        medium: 'llama3-70b-8192'
openai:
    gpt-3.5: 'gpt-3.5-turbo'

      
